export const severityMap = {
  "mild": [
    "(vertigo) paroymsal positional vertigo",
    ", ",
    ",\\\n       ",
    ",\\\n       \"athlete",
    "abdominal hernia",
    "abscess of nose",
    "abscess of the pharynx",
    "acariasis",
    "achalasia",
    "acne",
    "actinic keratosis",
    "acute stress reaction",
    "adhesive capsulitis of the shoulder",
    "adjustment reaction",
    "alcohol abuse",
    "alcohol intoxication",
    "alcohol withdrawal",
    "allergy",
    "allergy to animals",
    "alopecia",
    "alzheimer disease",
    "amyloidosis",
    "anal fissure",
    "angina",
    "ankylosing spondylitis",
    "anxiety",
    "aphakia",
    "arrhythmia",
    "asperger syndrome",
    "aspergillosis",
    "astigmatism",
    "atelectasis",
    "atonic bladder",
    "atrophic skin condition",
    "atrophic vaginitis",
    "attention deficit hyperactivity disorder (adhd)",
    "avascular necrosis",
    "balanitis",
    "bell palsy",
    "benign kidney cyst",
    "benign paroxysmal positional vertical (bppv)",
    "benign vaginal discharge (leukorrhea)",
    "bipolar disorder",
    "birth trauma",
    "bladder disorder",
    "blepharospasm",
    "bone disorder",
    "bone spur of the calcaneous",
    "bunion",
    "burn",
    "bursitis",
    "callus",
    "carbon monoxide poisoning",
    "carcinoid syndrome",
    "carpal tunnel syndrome",
    "cat scratch disease",
    "cerebral edema",
    "cerebral palsy",
    "cervical disorder",
    "cervical spondylosis",
    "cervicitis",
    "chalazion",
    "choledocholithiasis",
    "cholesteatoma",
    "chorioretinitis",
    "chronic back pain",
    "chronic inflammatory demyelinating polyneuropathy (cidp)",
    "chronic kidney disease",
    "chronic knee pain",
    "chronic pain disorder",
    "chronic rheumatic fever",
    "coagulation (bleeding) disorder",
    "cold sore",
    "colonic polyp",
    "common cold",
    "complex regional pain syndrome",
    "concussion",
    "conduct disorder",
    "conductive hearing loss",
    "conjunctivitis",
    "conjunctivitis due to allergy",
    "conjunctivitis due to virus",
    "conversion disorder",
    "corneal abrasion",
    "corneal disorder",
    "coronary atherosclerosis",
    "cranial nerve palsy",
    "crohn disease",
    "crushing injury",
    "cryptococcosis",
    "cryptorchidism",
    "cushing syndrome",
    "cyst of the eyelid",
    "cysticercosis",
    "degenerative disc disease",
    "delirium",
    "dental caries",
    "dermatitis due to sun exposure",
    "developmental disability",
    "deviated nasal septum",
    "diabetic kidney disease",
    "diaper rash",
    "dimorphic hemmorhoids(piles)",
    "diverticulosis",
    "drug abuse (barbiturates)",
    "drug abuse (cocaine)",
    "drug abuse (methamphetamine)",
    "drug abuse (opioids)",
    "drug withdrawal",
    "dry eye of unknown cause",
    "dyshidrosis",
    "dysthymic disorder",
    "eating disorder",
    "eczema",
    "edward syndrome",
    "emphysema",
    "endophthalmitis",
    "envenomation from spider or animal bite",
    "ependymoma",
    "epididymitis",
    "epilepsy",
    "erythema multiforme",
    "esophageal varices",
    "extrapyramidal effect of drugs",
    "eye alignment disorder",
    "factitious disorder",
    "female infertility of unknown cause",
    "fetal alcohol syndrome",
    "fibroadenoma",
    "fibrocystic breast disease",
    "fibromyalgia",
    "flat feet",
    "floaters",
    "fluid overload",
    "folate deficiency",
    "food allergy",
    "foreign body in the ear",
    "foreign body in the gastrointestinal tract",
    "foreign body in the throat",
    "foreign body in the vagina",
    "fungal infection",
    "g6pd enzyme deficiency",
    "galactorrhea of unknown cause",
    "gallstone",
    "ganglion cyst",
    "gastroesophageal reflux disease (gerd)",
    "gastroparesis",
    "genital herpes",
    "gerd",
    "glucocorticoid deficiency",
    "goiter",
    "gonorrhea",
    "gout",
    "granuloma inguinale",
    "guillain barre syndrome",
    "gum disease",
    "hammer toe",
    "headache after lumbar puncture",
    "heart block",
    "hemangioma",
    "hemarthrosis",
    "hematoma",
    "hemiplegia",
    "hemochromatosis",
    "hemophilia",
    "hepatitis due to a toxin",
    "herniated disk",
    "herpangina",
    "hiatal hernia",
    "hirschsprung disease",
    "histoplasmosis",
    "hpv",
    "huntington disease",
    "hydrocele of the testicle",
    "hydrocephalus",
    "hydronephrosis",
    "hypercholesterolemia",
    "hypergammaglobulinemia",
    "hyperhidrosis",
    "hyperlipidemia",
    "hyperopia",
    "hypocalcemia",
    "hypothyroidism",
    "idiopathic absence of menstruation",
    "idiopathic nonmenstrual bleeding",
    "ileus",
    "impetigo",
    "impulse control disorder",
    "indigestion",
    "induced abortion",
    "infectious gastroenteritis",
    "ingrown toe nail",
    "inguinal hernia",
    "injury of the ankle",
    "injury to internal organ",
    "injury to the abdomen",
    "injury to the arm",
    "injury to the finger",
    "injury to the hand",
    "injury to the hip",
    "injury to the knee",
    "injury to the leg",
    "injury to the shoulder",
    "injury to the spinal cord",
    "injury to the trunk",
    "insulin overdose",
    "intertrigo (skin condition)",
    "intestinal malabsorption",
    "intussusception",
    "itching of unknown cause",
    "joint effusion",
    "labyrinthitis",
    "laryngitis",
    "lateral epicondylitis (tennis elbow)",
    "lice",
    "lichen planus",
    "lichen simplex",
    "lumbago",
    "lung contusion",
    "lymphedema",
    "lymphogranuloma venereum",
    "macular degeneration",
    "magnesium deficiency",
    "marijuana abuse",
    "mastectomy",
    "melanoma",
    "meniere disease",
    "meningioma",
    "metabolic disorder",
    "missed abortion",
    "mitral valve disease",
    "mittelschmerz",
    "molluscum contagiosum",
    "mononucleosis",
    "mucositis",
    "multiple sclerosis",
    "muscle spasm",
    "muscular dystrophy",
    "myasthenia gravis",
    "myelodysplastic syndrome",
    "myoclonus",
    "myopia",
    "myositis",
    "narcolepsy",
    "nasal polyp",
    "neonatal jaundice",
    "nerve impingement near the shoulder",
    "neuralgia",
    "neurosis",
    "nonalcoholic liver disease (nash)",
    "normal pressure hydrocephalus",
    "nose disorder",
    "obesity",
    "obsessive compulsive disorder (ocd)",
    "obstructive sleep apnea (osa)",
    "omphalitis",
    "open wound due to trauma",
    "open wound from surgical incision",
    "open wound of the abdomen",
    "open wound of the arm",
    "open wound of the back",
    "open wound of the cheek",
    "open wound of the chest",
    "open wound of the eye",
    "open wound of the hand",
    "open wound of the head",
    "open wound of the jaw",
    "open wound of the knee",
    "open wound of the lip",
    "open wound of the mouth",
    "open wound of the neck",
    "open wound of the nose",
    "open wound of the shoulder",
    "optic neuritis",
    "oral leukoplakia",
    "oral mucosal lesion",
    "orthostatic hypotension",
    "osteoarthristis",
    "osteochondroma",
    "osteochondrosis",
    "osteoporosis",
    "otosclerosis",
    "overflow incontinence",
    "pain after an operation",
    "panic attack",
    "panic disorder",
    "parkinson disease",
    "paronychia",
    "pelvic organ prolapse",
    "pemphigus",
    "pericarditis",
    "peripheral arterial disease",
    "peripheral nerve disorder",
    "personality disorder",
    "peyronie disease",
    "pharyngitis",
    "pilonidal cyst",
    "pinguecula",
    "pituitary adenoma",
    "pituitary disorder",
    "pityriasis rosea",
    "plantar fasciitis",
    "pleural effusion",
    "pneumoconiosis",
    "poisoning due to analgesics",
    "poisoning due to antidepressants",
    "poisoning due to antihypertensives",
    "poisoning due to antimicrobial drugs",
    "poisoning due to ethylene glycol",
    "poisoning due to opioids",
    "poisoning due to sedatives",
    "polycystic kidney disease",
    "polycystic ovarian syndrome (pcos)",
    "polycythemia vera",
    "polymyalgia rheumatica",
    "premature atrial contractions (pacs)",
    "premature ovarian failure",
    "premature rupture of amniotic membrane",
    "premature ventricular contractions (pvcs)",
    "premenstrual tension syndrome",
    "presbyacusis",
    "priapism",
    "primary insomnia",
    "primary kidney disease",
    "primary thrombocythemia",
    "protein deficiency",
    "pseudotumor cerebri",
    "pterygium",
    "pulmonary congestion",
    "pulmonary eosinophilia",
    "pulmonic valve disease",
    "pyloric stenosis",
    "rectal disorder",
    "restless leg syndrome",
    "retinal detachment",
    "retinopathy due to high blood pressure",
    "rhabdomyolysis",
    "rheumatic fever",
    "rocky mountain spotted fever",
    "rotator cuff injury",
    "s ear)\",\\\n       ",
    "salivary gland disorder",
    "sarcoidosis",
    "scarlet fever",
    "sciatica",
    "scleritis",
    "scleroderma",
    "scoliosis",
    "scurvy",
    "seasonal allergies (hay fever)",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "sensorineural hearing loss",
    "shingles (herpes zoster)",
    "sialoadenitis",
    "sick sinus syndrome",
    "sjogren syndrome",
    "skin disorder",
    "skin pigmentation disorder",
    "spinocerebellar ataxia",
    "spondylitis",
    "spondylolisthesis",
    "spondylosis",
    "spontaneous abortion",
    "stenosis of the tear duct",
    "strep throat",
    "stress incontinence",
    "stricture of the esophagus",
    "stye",
    "substance-related mental disorder",
    "syndrome of inappropriate secretion of adh (siadh)",
    "syphilis",
    "syringomyelia",
    "systemic lupus erythematosis (sle)",
    "teething syndrome",
    "temporomandibular joint disorder",
    "tension headache",
    "thoracic outlet syndrome",
    "thrombocytopenia",
    "thrombophlebitis",
    "tietze syndrome",
    "tinnitus of unknown cause",
    "tonsillar hypertrophy",
    "tonsillitis",
    "tooth abscess",
    "tooth disorder",
    "torticollis",
    "tourette syndrome",
    "toxoplasmosis",
    "transient ischemic attack",
    "trichiasis",
    "trichinosis",
    "trigeminal neuralgia",
    "trigger finger (finger disorder)",
    "tuberous sclerosis",
    "turner syndrome",
    "urethral valves",
    "urethritis",
    "urge incontinence",
    "urinary tract infection",
    "uterine atony",
    "vacterl syndrome",
    "vaginal cyst",
    "vaginismus",
    "vaginitis",
    "varicose veins",
    "vasculitis",
    "vertebrobasilar insufficiency",
    "vesicoureteral reflux",
    "viral hepatitis",
    "viral warts",
    "vitamin a deficiency",
    "vitamin b12 deficiency",
    "vitreous degeneration",
    "vocal cord polyp",
    "volvulus",
    "von willebrand disease",
    "vulvar disorder",
    "vulvodynia",
    "white blood cell disease",
    "whooping cough",
    "wilson disease",
    "zenker diverticulum"
  ],
  "moderate": [
    "acute bronchospasm",
    "acute otitis media",
    "acute sinusitis",
    "anemia due to chronic kidney disease",
    "anemia due to malignancy",
    "anemia of chronic disease",
    "aphthous ulcer",
    "arthritis",
    "arthritis of the hip",
    "asthma",
    "atrial fibrillation",
    "atrial flutter",
    "autism",
    "bladder obstruction",
    "breast infection (mastitis)",
    "bronchial asthma",
    "cellulitis or abscess of mouth",
    "chicken pox",
    "chronic otitis media",
    "chronic sinusitis",
    "chronic ulcer",
    "cornea infection",
    "decubitus ulcer",
    "diabetes",
    "diabetic retinopathy",
    "dislocation of the ankle",
    "dislocation of the elbow",
    "dislocation of the finger",
    "dislocation of the foot",
    "dislocation of the knee",
    "dislocation of the patella",
    "dislocation of the shoulder",
    "drug reaction",
    "endometriosis",
    "fracture of the ankle",
    "fracture of the arm",
    "fracture of the finger",
    "fracture of the hand",
    "fracture of the leg",
    "fracture of the neck",
    "fracture of the patella",
    "fracture of the pelvis",
    "fracture of the rib",
    "fracture of the shoulder",
    "fungal infection of the hair",
    "fungal infection of the skin",
    "gastritis",
    "gastroduodenal ulcer",
    "gastroenteritis",
    "hashimoto thyroiditis",
    "hemolytic anemia",
    "hepatitis a",
    "hepatitis e",
    "hirsutism",
    "hypercalcemia",
    "hypernatremia",
    "hypertension",
    "hypertensive heart disease",
    "hyperthyroidism",
    "hypokalemia",
    "hyponatremia",
    "infection of open wound",
    "jaundice",
    "juvenile rheumatoid arthritis",
    "kidney stone",
    "male genitalia infection",
    "migraine",
    "oral thrush (yeast infection)",
    "osteoarthritis",
    "otitis media",
    "parathyroid adenoma",
    "peptic ulcer diseae",
    "peritonsillar abscess",
    "pinworm infection",
    "pneumonia",
    "poisoning due to antipsychotics",
    "postoperative infection",
    "postpartum depression",
    "problem during pregnancy",
    "prostatitis",
    "pseudohypoparathyroidism",
    "psoriasis",
    "pyelonephritis",
    "subacute thyroiditis",
    "threatened pregnancy",
    "thyroid disease",
    "ulcerative colitis",
    "uterine fibroids",
    "vaginal yeast infection"
  ],
  "severe": [
    "abdominal aortic aneurysm",
    "abscess of the lung",
    "acute glaucoma",
    "acute kidney injury",
    "acute pancreatitis",
    "adrenal cancer",
    "aids",
    "alcoholic hepatitis",
    "aplastic anemia",
    "bladder cancer",
    "bone cancer",
    "brain cancer",
    "breast cancer",
    "chronic cholestasis",
    "chronic glaucoma",
    "chronic obstructive pulmonary disease (copd)",
    "chronic pancreatitis",
    "cirrhosis",
    "colorectal cancer",
    "cystic fibrosis",
    "deep vein thrombosis (dvt)",
    "dengue",
    "dengue fever",
    "diabetic ketoacidosis",
    "ectopic pregnancy",
    "empyema",
    "encephalitis",
    "endometrial cancer",
    "esophageal cancer",
    "gastrointestinal hemorrhage",
    "glaucoma",
    "gynecomastia",
    "head and neck cancer",
    "heart attack",
    "heart failure",
    "hepatic encephalopathy",
    "hepatitis b",
    "hepatitis c",
    "hepatitis d",
    "hyperkalemia",
    "hyperosmotic hyperketotic state",
    "hypertrophic obstructive cardiomyopathy (hocm)",
    "hypoglycemia",
    "intestinal cancer",
    "intracerebral hemorrhage",
    "intracranial abscess",
    "intracranial hemorrhage",
    "ischemia of the bowel",
    "kaposi sarcoma",
    "kidney failure",
    "leukemia",
    "liver cancer",
    "lung cancer",
    "lymphoma",
    "malaria",
    "mastoiditis",
    "metastatic cancer",
    "necrotizing fasciitis",
    "orbital cellulitis",
    "osteomyelitis",
    "ovarian torsion",
    "paralysis (brain hemorrhage)",
    "peritonitis",
    "placental abruption",
    "prostate cancer",
    "pulmonary embolism",
    "pulmonary fibrosis",
    "sickle cell crisis",
    "skin cancer",
    "soft tissue sarcoma",
    "stomach cancer",
    "stroke",
    "subdural hemorrhage",
    "testicular cancer",
    "thoracic aortic aneurysm",
    "tuberculosis",
    "typhoid",
    "typhoid fever",
    "uterine cancer",
    "vitreous hemorrhage"
  ]
};

export const severityList = Object.entries(severityMap).flatMap(([sev, arr]) =>
  arr.map(name => ({ name, severity: sev }))
);

export function classifyDisease(name) {
  const n = name.toLowerCase().trim()
  if (severityMap.mild.some(x => x.toLowerCase() === n)) return 'mild'
  if (severityMap.moderate.some(x => x.toLowerCase() === n)) return 'moderate'
  if (severityMap.severe.some(x => x.toLowerCase() === n)) return 'severe'
  return null
}

